from __future__ import annotations

DEFAULT_DAILY_SELECT = 20
DEFAULT_MAX_RESULTS_PER_KEYWORD = 50
DEFAULT_MIN_SELECT = 3
DEFAULT_SCORE_THRESHOLD = 6.0
DEFAULT_SUMMARY_ARTIFACT_DIR = "data/paper-daily/summary-artifacts"
